/**
 * Adyen Payout API
 * A set of API endpoints that allow you to store payout details, confirm, or decline a payout.  For more information, refer to [Online payouts](https://docs.adyen.com/checkout/online-payouts).
 *
 * The version of the OpenAPI document: 52
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class AdditionalDataRatepay {
    /**
    * Amount the customer has to pay each month.
    */
    'ratepayInstallmentAmount'?: number;
    /**
    * Amount of the last installment.
    */
    'ratepayLastInstallmentAmount'?: number;
    /**
    * Interest rate of this installment. Double
    */
    'ratepayInterestRate'?: number;
    /**
    * Calendar day of the first payment.
    */
    'ratepayPaymentFirstday'?: number;
    /**
    * Identification name or number for the invoice, defined by the merchant.
    */
    'ratepaydataInvoiceId'?: string;
    /**
    * Invoice date, defined by the merchant. If not included, the invoice date is set to the delivery date.
    */
    'ratepaydataInvoiceDate'?: string;
    /**
    * Date the merchant delivered the goods to the customer.
    */
    'ratepaydataDeliveryDate'?: string;
    /**
    * Date by which the customer must settle the payment.
    */
    'ratepaydataDueDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ratepayInstallmentAmount",
            "baseName": "ratepay.installmentAmount",
            "type": "number"
        },
        {
            "name": "ratepayLastInstallmentAmount",
            "baseName": "ratepay.lastInstallmentAmount",
            "type": "number"
        },
        {
            "name": "ratepayInterestRate",
            "baseName": "ratepay.interestRate",
            "type": "number"
        },
        {
            "name": "ratepayPaymentFirstday",
            "baseName": "ratepay.paymentFirstday",
            "type": "number"
        },
        {
            "name": "ratepaydataInvoiceId",
            "baseName": "ratepaydata.invoiceId",
            "type": "string"
        },
        {
            "name": "ratepaydataInvoiceDate",
            "baseName": "ratepaydata.invoiceDate",
            "type": "string"
        },
        {
            "name": "ratepaydataDeliveryDate",
            "baseName": "ratepaydata.deliveryDate",
            "type": "string"
        },
        {
            "name": "ratepaydataDueDate",
            "baseName": "ratepaydata.dueDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AdditionalDataRatepay.attributeTypeMap;
    }
}

