/**
 * Adyen Payout API
 * A set of API endpoints that allow you to store payout details, confirm, or decline a payout.  For more information, refer to [Online payouts](https://docs.adyen.com/checkout/online-payouts).
 *
 * The version of the OpenAPI document: 52
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class AdditionalDataModifications {
    /**
    * This is the installment option selected by the shopper. It is required only if specified by the user.
    */
    'installmentPaymentDataSelectedInstallmentOption'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "installmentPaymentDataSelectedInstallmentOption",
            "baseName": "installmentPaymentData.selectedInstallmentOption",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AdditionalDataModifications.attributeTypeMap;
    }
}

