/**
 * Adyen for Platforms: Account API
 * The Account API provides endpoints for managing account-related entities on your platform. These related entities include account holders, accounts, bank accounts, shareholders, and KYC-related documents. The management operations include actions such as creation, retrieval, updating, and deletion of them.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay). ## Authentication To connect to the Account API, you must use basic authentication credentials of your web service user. If you don\'t have one, please contact the [Adyen Support Team](https://support.adyen.com/hc/en-us/requests/new). Then use its credentials to authenticate your request, for example:  ``` curl -U \"ws@MarketPlace.YourMarketPlace\":\"YourWsPassword\" \\ -H \"Content-Type: application/json\" \\ ... ``` Note that when going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).  ## Versioning The Account API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://cal-test.adyen.com/cal/services/Account/v5/createAccountHolder ```
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { KYCBankAccountCheckResult } from './kYCBankAccountCheckResult.ts';
 import { KYCCardCheckResult } from './kYCCardCheckResult.ts';
 import { KYCCheckResult } from './kYCCheckResult.ts';
 import { KYCShareholderCheckResult } from './kYCShareholderCheckResult.ts';

export class KYCVerificationResult {
    'accountHolder': KYCCheckResult;
    /**
    * The result(s) of the checks on the bank account(s).
    */
    'bankAccounts': Array<KYCBankAccountCheckResult>;
    /**
    * The result(s) of the checks on the card(s).
    */
    'cards': Array<KYCCardCheckResult>;
    /**
    * The result(s) of the checks on the shareholder(s).
    */
    'shareholders': Array<KYCShareholderCheckResult>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolder",
            "baseName": "accountHolder",
            "type": "KYCCheckResult"
        },
        {
            "name": "bankAccounts",
            "baseName": "bankAccounts",
            "type": "Array<KYCBankAccountCheckResult>"
        },
        {
            "name": "cards",
            "baseName": "cards",
            "type": "Array<KYCCardCheckResult>"
        },
        {
            "name": "shareholders",
            "baseName": "shareholders",
            "type": "Array<KYCShareholderCheckResult>"
        }    ];

    static getAttributeTypeMap() {
        return KYCVerificationResult.attributeTypeMap;
    }
}

