/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { LocalDate } from './localDate.ts';

export class AccountHolderUpcomingDeadlineNotificationContent {
    /**
    * The code of the account holder whom the event refers to.
    */
    'accountHolderCode'?: string;
    /**
    * The event name that will be trigger if no action is taken.
    */
    'event'?: AccountHolderUpcomingDeadlineNotificationContent.EventEnum;
    'executionDate'?: LocalDate;
    /**
    * The reason that leads to scheduling of the event.
    */
    'reason'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolderCode",
            "baseName": "accountHolderCode",
            "type": "string"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "AccountHolderUpcomingDeadlineNotificationContent.EventEnum"
        },
        {
            "name": "executionDate",
            "baseName": "executionDate",
            "type": "LocalDate"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountHolderUpcomingDeadlineNotificationContent.attributeTypeMap;
    }
}

export namespace AccountHolderUpcomingDeadlineNotificationContent {
    export enum EventEnum {
        AccessPii = <any> 'AccessPii',
        CloseAccount = <any> 'CloseAccount',
        CloseStores = <any> 'CloseStores',
        DeleteBankAccounts = <any> 'DeleteBankAccounts',
        DeletePayoutInstrumentTokens = <any> 'DeletePayoutInstrumentTokens',
        DeletePayoutMethods = <any> 'DeletePayoutMethods',
        DeleteShareholders = <any> 'DeleteShareholders',
        InactivateAccount = <any> 'InactivateAccount',
        RecalculateAccountStatusAndProcessingTier = <any> 'RecalculateAccountStatusAndProcessingTier',
        RefundNotPaidOutTransfers = <any> 'RefundNotPaidOutTransfers',
        ResolveEvents = <any> 'ResolveEvents',
        SaveAccountHolder = <any> 'SaveAccountHolder',
        SaveKYCCheckStatus = <any> 'SaveKYCCheckStatus',
        SuspendAccount = <any> 'SuspendAccount',
        UnSuspendAccount = <any> 'UnSuspendAccount',
        UpdateAccountHolderState = <any> 'UpdateAccountHolderState',
        Verification = <any> 'Verification'
    }
}
