/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { AccountEvent } from './accountEvent.ts';
 import { AccountPayoutState } from './accountPayoutState.ts';
 import { AccountProcessingState } from './accountProcessingState.ts';

export class AccountHolderStatus {
    /**
    * A list of events scheduled for the account holder.
    */
    'events': Array<AccountEvent>;
    'payoutState': AccountPayoutState;
    'processingState': AccountProcessingState;
    /**
    * The status of the account holder. >Permitted values: `Active`, `Inactive`, `Suspended`, `Closed`.
    */
    'status': AccountHolderStatus.StatusEnum;
    /**
    * The reason why the status was assigned to the account holder.
    */
    'statusReason': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<AccountEvent>"
        },
        {
            "name": "payoutState",
            "baseName": "payoutState",
            "type": "AccountPayoutState"
        },
        {
            "name": "processingState",
            "baseName": "processingState",
            "type": "AccountProcessingState"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountHolderStatus.StatusEnum"
        },
        {
            "name": "statusReason",
            "baseName": "statusReason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountHolderStatus.attributeTypeMap;
    }
}

export namespace AccountHolderStatus {
    export enum StatusEnum {
        Active = <any> 'Active',
        Closed = <any> 'Closed',
        Inactive = <any> 'Inactive',
        Suspended = <any> 'Suspended'
    }
}
