/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { Amount } from './amount.ts';

export class AccountProcessingState {
    /**
    * The reason why processing has been disabled.
    */
    'disableReason': string;
    /**
    * Indicates whether the processing of payments is allowed.
    */
    'disabled': boolean;
    'processedFrom': Amount;
    'processedTo': Amount;
    /**
    * The processing tier that the account holder occupies.
    */
    'tierNumber': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "disableReason",
            "baseName": "disableReason",
            "type": "string"
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean"
        },
        {
            "name": "processedFrom",
            "baseName": "processedFrom",
            "type": "Amount"
        },
        {
            "name": "processedTo",
            "baseName": "processedTo",
            "type": "Amount"
        },
        {
            "name": "tierNumber",
            "baseName": "tierNumber",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AccountProcessingState.attributeTypeMap;
    }
}

