/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class AccountEvent {
    /**
    * The event. >Permitted values: `InactivateAccount`, `RefundNotPaidOutTransfers`. For more information, refer to [Verification checks](https://docs.adyen.com/marketpay/onboarding-and-verification/verification-checks).
    */
    'event': AccountEvent.EventEnum;
    /**
    * The date on which the event will take place.
    */
    'executionDate': Date;
    /**
    * The reason why this event has been created.
    */
    'reason': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "AccountEvent.EventEnum"
        },
        {
            "name": "executionDate",
            "baseName": "executionDate",
            "type": "Date"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountEvent.attributeTypeMap;
    }
}

export namespace AccountEvent {
    export enum EventEnum {
        InactivateAccount = <any> 'InactivateAccount',
        RefundNotPaidOutTransfers = <any> 'RefundNotPaidOutTransfers'
    }
}
