/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { BankAccountDetail } from './bankAccountDetail.ts';
 import { BusinessDetails } from './businessDetails.ts';
 import { IndividualDetails } from './individualDetails.ts';
 import { PayoutMethod } from './payoutMethod.ts';
 import { ViasAddress } from './viasAddress.ts';

export class AccountHolderDetails {
    'address'?: ViasAddress;
    /**
    * Each of the bank accounts associated with the account holder. > Each array entry should represent one bank account. > For comprehensive detail regarding the required `BankAccountDetail` fields, please refer to the [KYC Verification documentation](https://docs.adyen.com/marketpay/onboarding-and-verification/verification-checks).
    */
    'bankAccountDetails'?: Array<BankAccountDetail>;
    'businessDetails'?: BusinessDetails;
    /**
    * The email address of the account holder.
    */
    'email': string;
    /**
    * The phone number of the account holder provided as a single string. It will be handled as a landline phone. **Examples:** \"0031 6 11 22 33 44\", \"+316/1122-3344\", \"(0031) 611223344\"
    */
    'fullPhoneNumber': string;
    'individualDetails'?: IndividualDetails;
    /**
    * The Merchant Category Code of the account holder. > If not specified in the request, this will be derived from the platform account (which is configured by Adyen).
    */
    'merchantCategoryCode'?: string;
    /**
    * A set of key and value pairs for general use by the account holder or merchant. The keys do not have specific names and may be used for storing miscellaneous data as desired. > The values being stored have a maximum length of eighty (80) characters and will be truncated if necessary. > Note that during an update of metadata, the omission of existing key-value pairs will result in the deletion of those key-value pairs.
    */
    'metadata'?: object;
    /**
    * Each of the card tokens associated with the account holder. > Each array entry should represent one card token. > For comprehensive detail regarding the required `CardToken` fields, please refer to the [KYC Verification documentation](https://docs.adyen.com/marketpay/onboarding-and-verification/verification-checks).
    */
    'payoutMethods'?: Array<PayoutMethod>;
    /**
    * The URL of the website of the account holder.
    */
    'webAddress': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "ViasAddress"
        },
        {
            "name": "bankAccountDetails",
            "baseName": "bankAccountDetails",
            "type": "Array<BankAccountDetail>"
        },
        {
            "name": "businessDetails",
            "baseName": "businessDetails",
            "type": "BusinessDetails"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "fullPhoneNumber",
            "baseName": "fullPhoneNumber",
            "type": "string"
        },
        {
            "name": "individualDetails",
            "baseName": "individualDetails",
            "type": "IndividualDetails"
        },
        {
            "name": "merchantCategoryCode",
            "baseName": "merchantCategoryCode",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "payoutMethods",
            "baseName": "payoutMethods",
            "type": "Array<PayoutMethod>"
        },
        {
            "name": "webAddress",
            "baseName": "webAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountHolderDetails.attributeTypeMap;
    }
}

