/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { ErrorFieldType } from './errorFieldType.ts';

export class BeneficiarySetupNotificationContent {
    /**
    * The code of the beneficiary account.
    */
    'destinationAccountCode': string;
    /**
    * The code of the beneficiary Account Holder.
    */
    'destinationAccountHolderCode': string;
    /**
    * A listing of the invalid fields which have caused the Setup Beneficiary request to fail. If this is empty, the Setup Beneficiary request has succeeded.
    */
    'invalidFields'?: Array<ErrorFieldType>;
    /**
    * The reference provided by the merchant.
    */
    'merchantReference'?: string;
    /**
    * The code of the benefactor account.
    */
    'sourceAccountCode': string;
    /**
    * The code of the benefactor Account Holder.
    */
    'sourceAccountHolderCode': string;
    /**
    * The date on which the beneficiary was set up and funds transferred from benefactor to beneficiary.
    */
    'transferDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "destinationAccountCode",
            "baseName": "destinationAccountCode",
            "type": "string"
        },
        {
            "name": "destinationAccountHolderCode",
            "baseName": "destinationAccountHolderCode",
            "type": "string"
        },
        {
            "name": "invalidFields",
            "baseName": "invalidFields",
            "type": "Array<ErrorFieldType>"
        },
        {
            "name": "merchantReference",
            "baseName": "merchantReference",
            "type": "string"
        },
        {
            "name": "sourceAccountCode",
            "baseName": "sourceAccountCode",
            "type": "string"
        },
        {
            "name": "sourceAccountHolderCode",
            "baseName": "sourceAccountHolderCode",
            "type": "string"
        },
        {
            "name": "transferDate",
            "baseName": "transferDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return BeneficiarySetupNotificationContent.attributeTypeMap;
    }
}

