/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { ErrorFieldType } from './errorFieldType.ts';

export class CloseAccountResponse {
    /**
    * The account code of the account that is closed.
    */
    'accountCode'?: string;
    /**
    * Contains field validation errors that would prevent requests from being processed.
    */
    'invalidFields'?: Array<ErrorFieldType>;
    /**
    * The reference of a request.  Can be used to uniquely identify the request.
    */
    'pspReference': string;
    /**
    * The result code.
    */
    'resultCode'?: string;
    /**
    * The new status of the account. >Permitted values: `Active`, `Inactive`, `Suspended`, `Closed`.
    */
    'status': CloseAccountResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountCode",
            "baseName": "accountCode",
            "type": "string"
        },
        {
            "name": "invalidFields",
            "baseName": "invalidFields",
            "type": "Array<ErrorFieldType>"
        },
        {
            "name": "pspReference",
            "baseName": "pspReference",
            "type": "string"
        },
        {
            "name": "resultCode",
            "baseName": "resultCode",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CloseAccountResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return CloseAccountResponse.attributeTypeMap;
    }
}

export namespace CloseAccountResponse {
    export enum StatusEnum {
        Active = <any> 'Active',
        Closed = <any> 'Closed',
        Inactive = <any> 'Inactive',
        Suspended = <any> 'Suspended'
    }
}
