/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { Amount } from './amount.ts';
 import { LocalDate } from './localDate.ts';
 import { OperationStatus } from './operationStatus.ts';

export class DirectDebitInitiatedNotificationContent {
    /**
    * The code of the account.
    */
    'accountCode': string;
    'amount': Amount;
    'debitInitiationDate'?: LocalDate;
    /**
    * The code of the merchant account.
    */
    'merchantAccountCode': string;
    'status'?: OperationStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountCode",
            "baseName": "accountCode",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount"
        },
        {
            "name": "debitInitiationDate",
            "baseName": "debitInitiationDate",
            "type": "LocalDate"
        },
        {
            "name": "merchantAccountCode",
            "baseName": "merchantAccountCode",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OperationStatus"
        }    ];

    static getAttributeTypeMap() {
        return DirectDebitInitiatedNotificationContent.attributeTypeMap;
    }
}

