/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class FieldType {
    /**
    * The full name of the property.
    */
    'field'?: string;
    /**
    * The type of the field.
    */
    'fieldName'?: FieldType.FieldNameEnum;
    /**
    * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
    */
    'shareholderCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "fieldName",
            "baseName": "fieldName",
            "type": "FieldType.FieldNameEnum"
        },
        {
            "name": "shareholderCode",
            "baseName": "shareholderCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FieldType.attributeTypeMap;
    }
}

export namespace FieldType {
    export enum FieldNameEnum {
        AccountCode = <any> 'accountCode',
        AccountHolderCode = <any> 'accountHolderCode',
        AccountHolderDetails = <any> 'accountHolderDetails',
        AccountNumber = <any> 'accountNumber',
        AccountStateType = <any> 'accountStateType',
        AccountStatus = <any> 'accountStatus',
        AccountType = <any> 'accountType',
        Address = <any> 'address',
        BankAccount = <any> 'bankAccount',
        BankAccountCode = <any> 'bankAccountCode',
        BankAccountName = <any> 'bankAccountName',
        BankAccountUUID = <any> 'bankAccountUUID',
        BankBicSwift = <any> 'bankBicSwift',
        BankCity = <any> 'bankCity',
        BankCode = <any> 'bankCode',
        BankName = <any> 'bankName',
        BankStatement = <any> 'bankStatement',
        BranchCode = <any> 'branchCode',
        BusinessContact = <any> 'businessContact',
        CardToken = <any> 'cardToken',
        CheckCode = <any> 'checkCode',
        City = <any> 'city',
        CompanyRegistration = <any> 'companyRegistration',
        Country = <any> 'country',
        CountryCode = <any> 'countryCode',
        Currency = <any> 'currency',
        CurrencyCode = <any> 'currencyCode',
        DateOfBirth = <any> 'dateOfBirth',
        Description = <any> 'description',
        DestinationAccountCode = <any> 'destinationAccountCode',
        Document = <any> 'document',
        DocumentExpirationDate = <any> 'documentExpirationDate',
        DocumentIssuerCountry = <any> 'documentIssuerCountry',
        DocumentIssuerState = <any> 'documentIssuerState',
        DocumentName = <any> 'documentName',
        DocumentNumber = <any> 'documentNumber',
        DocumentType = <any> 'documentType',
        DoingBusinessAs = <any> 'doingBusinessAs',
        DrivingLicence = <any> 'drivingLicence',
        DrivingLicenceBack = <any> 'drivingLicenceBack',
        DrivingLicense = <any> 'drivingLicense',
        Email = <any> 'email',
        FirstName = <any> 'firstName',
        FullPhoneNumber = <any> 'fullPhoneNumber',
        Gender = <any> 'gender',
        HopWebserviceUser = <any> 'hopWebserviceUser',
        HouseNumberOrName = <any> 'houseNumberOrName',
        Iban = <any> 'iban',
        IdCard = <any> 'idCard',
        IdCardBack = <any> 'idCardBack',
        IdCardFront = <any> 'idCardFront',
        IdNumber = <any> 'idNumber',
        IdentityDocument = <any> 'identityDocument',
        IndividualDetails = <any> 'individualDetails',
        LastName = <any> 'lastName',
        LegalBusinessName = <any> 'legalBusinessName',
        LegalEntity = <any> 'legalEntity',
        LegalEntityType = <any> 'legalEntityType',
        MerchantAccount = <any> 'merchantAccount',
        MerchantCategoryCode = <any> 'merchantCategoryCode',
        MerchantReference = <any> 'merchantReference',
        MicroDeposit = <any> 'microDeposit',
        Name = <any> 'name',
        Nationality = <any> 'nationality',
        OriginalReference = <any> 'originalReference',
        OwnerCity = <any> 'ownerCity',
        OwnerCountryCode = <any> 'ownerCountryCode',
        OwnerHouseNumberOrName = <any> 'ownerHouseNumberOrName',
        OwnerName = <any> 'ownerName',
        OwnerPostalCode = <any> 'ownerPostalCode',
        OwnerState = <any> 'ownerState',
        OwnerStreet = <any> 'ownerStreet',
        Passport = <any> 'passport',
        PassportNumber = <any> 'passportNumber',
        PayoutMethodCode = <any> 'payoutMethodCode',
        PersonalData = <any> 'personalData',
        PhoneCountryCode = <any> 'phoneCountryCode',
        PhoneNumber = <any> 'phoneNumber',
        PostalCode = <any> 'postalCode',
        PrimaryCurrency = <any> 'primaryCurrency',
        Reason = <any> 'reason',
        RegistrationNumber = <any> 'registrationNumber',
        ReturnUrl = <any> 'returnUrl',
        Schedule = <any> 'schedule',
        Shareholder = <any> 'shareholder',
        ShareholderCode = <any> 'shareholderCode',
        SocialSecurityNumber = <any> 'socialSecurityNumber',
        SourceAccountCode = <any> 'sourceAccountCode',
        StateOrProvince = <any> 'stateOrProvince',
        Status = <any> 'status',
        Store = <any> 'store',
        StoreDetail = <any> 'storeDetail',
        StoreName = <any> 'storeName',
        StoreReference = <any> 'storeReference',
        Street = <any> 'street',
        TaxId = <any> 'taxId',
        Tier = <any> 'tier',
        TierNumber = <any> 'tierNumber',
        TransferCode = <any> 'transferCode',
        Unknown = <any> 'unknown',
        Value = <any> 'value',
        VirtualAccount = <any> 'virtualAccount',
        VisaNumber = <any> 'visaNumber',
        WebAddress = <any> 'webAddress'
    }
}
