/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { KYCCheckSummary } from './kYCCheckSummary.ts';

export class KYCCheckStatusData {
    /**
    * A list of the fields required for execution of the check.
    */
    'requiredFields': Array<string>;
    /**
    * The status of the check. >Permitted Values: `DATA_PROVIDED`, `PASSED`, `PENDING`, `AWAITING_DATA`, `RETRY_LIMIT_REACHED`, `INVALID_DATA`, `FAILED`.
    */
    'status': KYCCheckStatusData.StatusEnum;
    'summary': KYCCheckSummary;
    /**
    * The type of check. >Permitted Values: `COMPANY_VERIFICATION`, `IDENTITY_VERIFICATION`, `PASSPORT_VERIFICATION`, `BANK_ACCOUNT_VERIFICATION`, `NONPROFIT_VERIFICATION`.
    */
    'type': KYCCheckStatusData.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requiredFields",
            "baseName": "requiredFields",
            "type": "Array<string>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "KYCCheckStatusData.StatusEnum"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "KYCCheckSummary"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "KYCCheckStatusData.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return KYCCheckStatusData.attributeTypeMap;
    }
}

export namespace KYCCheckStatusData {
    export enum StatusEnum {
        AWAITINGDATA = <any> 'AWAITING_DATA',
        DATAPROVIDED = <any> 'DATA_PROVIDED',
        FAILED = <any> 'FAILED',
        INVALIDDATA = <any> 'INVALID_DATA',
        PASSED = <any> 'PASSED',
        PENDING = <any> 'PENDING',
        PENDINGREVIEW = <any> 'PENDING_REVIEW',
        RETRYLIMITREACHED = <any> 'RETRY_LIMIT_REACHED',
        UNCHECKED = <any> 'UNCHECKED'
    }
    export enum TypeEnum {
        BANKACCOUNTVERIFICATION = <any> 'BANK_ACCOUNT_VERIFICATION',
        COMPANYVERIFICATION = <any> 'COMPANY_VERIFICATION',
        IDENTITYVERIFICATION = <any> 'IDENTITY_VERIFICATION',
        NONPROFITVERIFICATION = <any> 'NONPROFIT_VERIFICATION',
        PASSPORTVERIFICATION = <any> 'PASSPORT_VERIFICATION'
    }
}
