/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class PayoutScheduleResponse {
    /**
    * The date of the next scheduled payout.
    */
    'nextScheduledPayout': Date;
    /**
    * The payout schedule of the account. >Permitted values: `DEFAULT`, `HOLD`, `DAILY`, `WEEKLY`, `MONTHLY`.
    */
    'schedule': PayoutScheduleResponse.ScheduleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextScheduledPayout",
            "baseName": "nextScheduledPayout",
            "type": "Date"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "PayoutScheduleResponse.ScheduleEnum"
        }    ];

    static getAttributeTypeMap() {
        return PayoutScheduleResponse.attributeTypeMap;
    }
}

export namespace PayoutScheduleResponse {
    export enum ScheduleEnum {
        BIWEEKLYON1STAND15THATMIDNIGHT = <any> 'BIWEEKLY_ON_1ST_AND_15TH_AT_MIDNIGHT',
        BIWEEKLYON1STAND15THATNOON = <any> 'BIWEEKLY_ON_1ST_AND_15TH_AT_NOON',
        DAILY = <any> 'DAILY',
        DAILY6PM = <any> 'DAILY_6PM',
        DAILYAU = <any> 'DAILY_AU',
        DAILYEU = <any> 'DAILY_EU',
        DAILYUS = <any> 'DAILY_US',
        DEFAULT = <any> 'DEFAULT',
        EVERY6HOURSFROMMIDNIGHT = <any> 'EVERY_6_HOURS_FROM_MIDNIGHT',
        HOLD = <any> 'HOLD',
        MONTHLY = <any> 'MONTHLY',
        WEEKLY = <any> 'WEEKLY',
        WEEKLYONTUEFRIMIDNIGHT = <any> 'WEEKLY_ON_TUE_FRI_MIDNIGHT',
        YEARLY = <any> 'YEARLY'
    }
}
