/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class PersonalDocumentData {
    /**
    * The expiration date of the document. The date should be in ISO-8601 format yyyy-mm-dd (e.g. 2000-01-31).
    */
    'expirationDate'?: string;
    /**
    * The two-character country code of the issuer. >The permitted country codes are defined in ISO-3166-1 alpha-2 (e.g. \'NL\').
    */
    'issuerCountry'?: string;
    /**
    * The state issued the document (if applicable)
    */
    'issuerState'?: string;
    /**
    * The number of the document. Delete the given type if the value empty.
    */
    'number': string;
    /**
    * The type of the document. More then one item pert type does not allowed. Valid values: ID, PASSPORT, VISA, DRIVINGLICENSE
    */
    'type': PersonalDocumentData.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "string"
        },
        {
            "name": "issuerCountry",
            "baseName": "issuerCountry",
            "type": "string"
        },
        {
            "name": "issuerState",
            "baseName": "issuerState",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PersonalDocumentData.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PersonalDocumentData.attributeTypeMap;
    }
}

export namespace PersonalDocumentData {
    export enum TypeEnum {
        DRIVINGLICENSE = <any> 'DRIVINGLICENSE',
        ID = <any> 'ID',
        PASSPORT = <any> 'PASSPORT',
        SOCIALSECURITY = <any> 'SOCIALSECURITY',
        VISA = <any> 'VISA'
    }
}
