/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { ErrorFieldType } from './errorFieldType.ts';
 import { RefundResult } from './refundResult.ts';
 import { Transaction } from './transaction.ts';

export class ScheduledRefundsNotificationContent {
    /**
    * The code of the account.
    */
    'accountCode': string;
    /**
    * The code of the Account Holder.
    */
    'accountHolderCode': string;
    /**
    * Invalid fields list.
    */
    'invalidFields'?: Array<ErrorFieldType>;
    'lastPayout': Transaction;
    /**
    * A list of the refunds that have been scheduled and their results.
    */
    'refundResults': Array<RefundResult>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountCode",
            "baseName": "accountCode",
            "type": "string"
        },
        {
            "name": "accountHolderCode",
            "baseName": "accountHolderCode",
            "type": "string"
        },
        {
            "name": "invalidFields",
            "baseName": "invalidFields",
            "type": "Array<ErrorFieldType>"
        },
        {
            "name": "lastPayout",
            "baseName": "lastPayout",
            "type": "Transaction"
        },
        {
            "name": "refundResults",
            "baseName": "refundResults",
            "type": "Array<RefundResult>"
        }    ];

    static getAttributeTypeMap() {
        return ScheduledRefundsNotificationContent.attributeTypeMap;
    }
}

