/**
 * Adyen for Platforms: Notifications
 * The Notification API sends notifications to the endpoints specified in a given subscription. Subscriptions are managed through the Notification Configuration API. The API specifications listed here detail the format of each notification.  For more information, refer to our [documentation](https://docs.adyen.com/marketpay/marketpay-notifications).
 *
 * The version of the OpenAPI document: 5
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 
 import { PersonalDocumentData } from './personalDocumentData.ts';

export class ViasPersonalData {
    /**
    * The date of birth of the person. The date should be in ISO-8601 format yyyy-mm-dd (e.g. 2000-01-31).
    */
    'dateOfBirth'?: string;
    /**
    * Key value pairs of document type and identify numbers
    */
    'documentData'?: Array<PersonalDocumentData>;
    /**
    * The nationality of the person represented by a two-character country code. >The permitted country codes are defined in ISO-3166-1 alpha-2 (e.g. \'NL\').
    */
    'nationality'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateOfBirth",
            "baseName": "dateOfBirth",
            "type": "string"
        },
        {
            "name": "documentData",
            "baseName": "documentData",
            "type": "Array<PersonalDocumentData>"
        },
        {
            "name": "nationality",
            "baseName": "nationality",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ViasPersonalData.attributeTypeMap;
    }
}

