/**
 * Adyen Checkout API
 * Adyen Checkout API provides a simple and flexible way to initiate and authorise online payments. You can use the same integration for payments made with cards (including 3D Secure), mobile wallets, and local payment methods (for example, iDEAL and Sofort).  This API reference provides information on available endpoints and how to interact with them. To learn more about the API, visit [Checkout documentation](https://docs.adyen.com/checkout).  ## Authentication Each request to the Checkout API must be signed with an API key. For this, obtain an API Key from your Customer Area, as described in [How to get the API key](https://docs.adyen.com/user-management/how-to-get-the-api-key). Then set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: Your_Checkout_API_key\" \\ ... ``` Note that when going live, you need to generate a new API Key to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).  ## Versioning Checkout API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://checkout-test.adyen.com/v52/payments ```
 *
 * The version of the OpenAPI document: 52
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 

export class ResponseAdditionalDataInstallments {
    /**
    * The number of installments that the payment amount should be charged with.  Example: 5 > Only relevant for card payments in countries that support installments.
    */
    'installmentsValue'?: string;
    /**
    * Type of installment. The value of `installmentType` should be **IssuerFinanced**.
    */
    'installmentPaymentDataInstallmentType'?: string;
    /**
    * Possible values: * PayInInstallmentsOnly * PayInFullOnly * PayInFullOrInstallments
    */
    'installmentPaymentDataPaymentOptions'?: string;
    /**
    * Total number of installments possible for this payment.
    */
    'installmentPaymentDataOptionItemNrNumberOfInstallments'?: string;
    /**
    * Interest rate for the installment period.
    */
    'installmentPaymentDataOptionItemNrInterestRate'?: string;
    /**
    * Installment fee amount in minor units.
    */
    'installmentPaymentDataOptionItemNrInstallmentFee'?: string;
    /**
    * Annual interest rate.
    */
    'installmentPaymentDataOptionItemNrAnnualPercentageRate'?: string;
    /**
    * First Installment Amount in minor units.
    */
    'installmentPaymentDataOptionItemNrFirstInstallmentAmount'?: string;
    /**
    * Subsequent Installment Amount in minor units.
    */
    'installmentPaymentDataOptionItemNrSubsequentInstallmentAmount'?: string;
    /**
    * Minimum number of installments possible for this payment.
    */
    'installmentPaymentDataOptionItemNrMinimumNumberOfInstallments'?: string;
    /**
    * Maximum number of installments possible for this payment.
    */
    'installmentPaymentDataOptionItemNrMaximumNumberOfInstallments'?: string;
    /**
    * Total amount in minor units.
    */
    'installmentPaymentDataOptionItemNrTotalAmountDue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "installmentsValue",
            "baseName": "installments.value",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataInstallmentType",
            "baseName": "installmentPaymentData.installmentType",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataPaymentOptions",
            "baseName": "installmentPaymentData.paymentOptions",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrNumberOfInstallments",
            "baseName": "installmentPaymentData.option[itemNr].numberOfInstallments",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrInterestRate",
            "baseName": "installmentPaymentData.option[itemNr].interestRate",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrInstallmentFee",
            "baseName": "installmentPaymentData.option[itemNr].installmentFee",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrAnnualPercentageRate",
            "baseName": "installmentPaymentData.option[itemNr].annualPercentageRate",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrFirstInstallmentAmount",
            "baseName": "installmentPaymentData.option[itemNr].firstInstallmentAmount",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrSubsequentInstallmentAmount",
            "baseName": "installmentPaymentData.option[itemNr].subsequentInstallmentAmount",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrMinimumNumberOfInstallments",
            "baseName": "installmentPaymentData.option[itemNr].minimumNumberOfInstallments",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrMaximumNumberOfInstallments",
            "baseName": "installmentPaymentData.option[itemNr].maximumNumberOfInstallments",
            "type": "string"
        },
        {
            "name": "installmentPaymentDataOptionItemNrTotalAmountDue",
            "baseName": "installmentPaymentData.option[itemNr].totalAmountDue",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseAdditionalDataInstallments.attributeTypeMap;
    }
}

